version: '3.1'
services:
  accelerexdb:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - accelerex-postgres:/var/lib/postgresql/data
volumes:
  accelerex-postgres:
